config/routes.rb
NewsBlock::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :news, except: :destroy do
    collection do
      get :by_votes
      get :my
    end
    member do
      post :vote
      post :delete
    end
  end

  root to: 'home#lets_go'

end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user

  attr_accessible :content, :title

  has_reputation :votes, source: :user, aggregated_by: :sum

  scope :by_date, order('created_at DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable, :trackable,
  # :lockable, :timeoutable and :omniauthable, :rememberable, :recoverable
  devise :database_authenticatable,
         :validatable

  has_many :news

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password

  def self.authenticate options
    user = find_by_email options[:email]
    user if user && user.valid_password?(options[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def lets_go
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate_user!, except: [:index,
                                              :by_votes,
                                              :show]

  layout false

  NEWS_PER_PAGE = 10

  def new
    @newska = News.new
  end

  def edit
    newska
  end

  def create
    current_user.news.create! params[:news]
    render nothing: true
  end

  def update
    newska.update_attributes params[:news]
    render nothing: true
  end

  def vote
    value = params[:type] == 'up' ? 1 : -1
    @newska = News.find params[:id]
    @newska.add_or_update_evaluation :votes,
                                     value,
                                     current_user
    render partial: 'newska', locals: { newska: @newska }
  end

  def index
    @news = News.by_date.paginate page: params[:page],
                          per_page: NEWS_PER_PAGE
  end

  def by_votes
    @news = News.find_with_reputation(:votes,
                                      :all,
                                      order: 'votes DESC')
                .paginate page: params[:page],
                          per_page: NEWS_PER_PAGE
    render 'index'
  end

  def my
    @news = current_user.news.paginate page: params[:page],
                                       per_page: NEWS_PER_PAGE
    render 'index'
  end

  def show
    @newska = News.find params[:id]
  end

  def delete
    newska.destroy
    render nothing: true
  end

  protected

  def newska
    @newska ||= current_user.news.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_filter :authenticate_user!, only: :destroy

  def new
    @user = User.new
    render layout: false
  end

  def create
    @user = (User.authenticate(params[:user]) || User.create(params[:user]))
    if @user.try :id
      sign_in @user
      flash[:alert] = 'You were signed in successfully'
    else
      flash[:error] = 'There are some errors'
    end
    redirect_to root_path
  end

  def destroy
    sign_out current_user
    flash[:alert] = 'You were signed out successfully'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_hello.html.erb
<strong>Hello <%= current_user.email %></strong>
<%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn', id: 'logout' %>

app/views/home/_login.html.erb
<span id="login" class="btn">Log in</span>
<div id="login_form" data-path="<%= new_user_session_path %>"></div>

app/views/home/lets_go.html.erb
<% if current_user %>
  <%= render 'hello' %>
<% else %>
  <%= render 'login' %>
<% end %>
<% if current_user %>
  <%= link_to "Add News", new_news_path, id: "add_news", class: 'btn' %>
  <div id="show_news_form"></div>
<% end %>
<div id='navigation'>
  <%= link_to "By Date", news_index_path, class: :sort_news %>
  | <%= link_to "By Votes", by_votes_news_index_path, class: :sort_news %>
  <% if current_user %>
    | <%= link_to "My News", my_news_index_path, class: :sort_news %>
  <% end %>
</div>
<div id="news" data-path="<%= news_index_path %>"></div>
<div id="detailed_newska"></div>

<script type='text/javascript'>
  $(function(){
    var news = $('#news');
    $.get(news.data('path'), function(data){
      news.html(data);
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:alert] %>
  <%= content_tag :div, flash[:alert], class: 'alert alert-success' %>
<% end %>
<% if flash[:error] %>
  <%= content_tag :div, flash[:error], class: 'alert alert-error' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<div class="back container">
  <div class="manage_form well">
    <span class='close'>x</span>
    <%= form_for newska, html: { class: 'news_form' } do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_area :content %><br />
      <%= f.submit 'Post', class: 'btn btn-submit' %>
    <% end %>
  </div>
</div>

app/views/news/_newska.html.erb
<div class="newska_title">
  <%= newska.title %>
</div>
<% if current_user == newska.user %>
  <%= link_to 'del', delete_news_path(newska), class: 'delete_news btn', confirm: 'Are you sure?' %>
  <%= link_to 'edit', edit_news_path(newska), class: 'edit_news btn' %>
<% end %>
<div class="newska_content">
  <%= truncate newska.content, length: 100 %>
</div>
<a class="show_newska">Read more</a>
<span class="votes">
  <%= pluralize newska.reputation_for(:votes).to_i, 'vote' %>
  <% if current_user %>
    <% ['up', 'down'].each do |type| %>
      | <%= link_to type, vote_news_path(newska, type: type), class: 'vote' %>
    <% end %>
  <% end %>
</span>

app/views/news/edit.html.erb
<%= render 'form', newska: @newska %>

app/views/news/index.html.erb
<% @news.each do |newska| %>
  <div class="newska well well-small" data-path="<%= news_path newska %>">
    <%= render 'news/newska', newska: newska %>
  </div>
<% end %>
<%= will_paginate @news %>

app/views/news/new.html.erb
<span class='close'>x</span>
<%= form_for @newska do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit 'Post' %>
<% end %>

app/views/news/show.html.erb
<div class="back container">
  <div class='show_form well'>
    <span class='close'>x</span>
    <h4><%= @newska.title %></h4>
    <%= @newska.content %>
    <p><br />
    posted by <%= @newska.user.email %>
    at <%= @newska.created_at.to_s :db %>
  </div>
</div>